server:
  port: 8080

spring:
  redis:
    host: 127.0.0.1
    port: 21879
    password: root
    database: 0
    timeout: 3S

# 告警配置
alarm:
  serverj:
    url: "https://sc.ftqq.com/<your github serkey>.send" #文档：　http://sc.ftqq.com/3.version

